export interface IAgent {
    AGT_ID: string;
    AGT_CODE : string;
    AGT_CODE_ID: number;
    AGT_TYPE_ID: number;
    AGT_MDRT_STATUS : number;
    AGT_MDRT_YEAR : number;
    AGT_SYSTEM_ID : string;
    AGT_SUB_CODE : string;
    AGT_LINE_OF_BUSINESS  : number;
    AGT_CHANNEL : string;
    AGT_LEVEL : number;
    AGT_LANGUAGE : number;
    AGT_SUPER_CODE : string;
    AGT_TITLE : string;
    AGT_FIRST_NAME : string;
    AGT_LAST_NAME : string;
    AGT_ADD1 : string;
    AGT_ADD2 : string;
    AGT_ADD3 : string;
    AGT_NIC_NO : string;
    AGT_DOB : Date;
    AGT_MOBILE : string;
    AGT_TEL_NO : string;
    AGT_FAX_NO : string;
    AGT_BRANCH_CODE : string;
    AGT_BANK_ID : number;
    AGT_BANK_BRANCH_ID : number;
    AGT_BANK_ACC_NO : string;
    AGT_ID_ISSUED : number;
    AGT_ID_ISSUED_DATE : Date;
    AGT_APPOINT_DATE : Date;
    AGT_SLII_EXAM : number;
    AGT_SLII_EXAM_DATE : Date;

    AGT_AGMT_DATE_RECEIVED : Date;
    AGT_AGMT_DATE_ISSUED : Date;
    AGT_APP_DATE_RECEIVED : Date;
    AGT_APP_DATE_ISSUED : Date;
    
    AGT_TRNS_BRANCH_CODE : string;
    AGT_TRNS_BRANCH_DATE : Date;
    AGT_STOP_COMM_DATE : Date;
    AGT_STOP_COMM_REASON : string;
    AGT_RELEASE_COMM_DATE : Date;
    AGT_RELEASE_COMM_REASON : string;
    AGT_CUSTOMER_COMPLAIN : string;
    AGT_TERMINATE_NOTICE_DATE : Date;
    AGT_TERMINATE_DATE : Date;
    AGT_TERMINATE_REASON : string;
    AGT_BLACK_LISTED_DATE : Date;
    AGT_DUES_TO_COMPANY : string;
    AGT_REJOINED_DATE : Date;
    AGT_REMARKS : string;
    AGT_BUSINESS_TYPE: number;
    AGT_LEVEL_CODE: string;
    AGT_LEADER_CODE: string;
    AGT_STATUS: number;
    AGT_TERMINATE_STATUS: number;
    AGT_STOP_COMM_STATUS: number;
    AGT_ISS_STATUS: number;
    AGT_ISS_AMOUNT: number;
    AGT_ISS_GIVEN_DATE: Date;
    AGT_ISS_CLOSE_DATE: Date;
    AGT_RETAINER_STATUS: number;
    AGT_RETAINER_AMOUNT: number;
    AGT_RETAINER_GIVEN_DATE: Date;
    AGT_RETAINER_CLOSE_DATE: Date;
    AGT_LEADER_AGENT_CODE_V: string;
    AGT_LEADER_LEADER_CODE_V: string;
    AGT_LEADER_AGENT_CODE_H: string;
    AGT_LEADER_LEADER_CODE_H: string;
    AGT_CREATED_BY: string;

}