export interface IPID { 
    PidReceiptNo:string  ;
    PidReceiptDate:string  ;
    PidCustomerName:string  ;
    PidProposalNo:string  ;
    PidPolicyNo:string  ;
    PidReceiptAmt:number  ;
    // PidPaymentMtd:string  ;
    // PidBranch:string  ;
    // PidBankCode:string  ;
    PidAgtCode:string  ;
    // PidTimeSlab:string  ;
    // PidTerm:number  ;
    // PidInstallmentAmt:number  ;
    // PidTable:number  ;
    // PidPayFreq:string  ;
    // PidConfirmInd:string  ;
    // PidConfirmAmt:number  ;
    // PidRefundInd:string  ;
     PidAvailableAmt:number  ;
    // PidReverseInd:string  ;
    // PidCommCalInd:string  ;
    // PidConfirmBy:string  ;
    // PidConfirmDate:string  ;
    // PidLastModifiedBy:string  ;
    // PidLastModifiedDate:string  ;
    // PidLastModifiedReson:string  ;
    // PidIsHeldReceipt:string  ;
    // PidReceiptType:string  ;
    // PidTempField1:string  ;
    // PidTempField2:number  ;
    // PidTempField3:string  ;
    // PidChequeRetInd:string  ;
    // PidProductCode:string  ;
    // PidPolicyBank:string  ;
    // PidPolicyYear:number  ;
    // PidUploadDate:string  ;
    // PidRvNo:string  ;
    // PidPolicyFee:number  ;
    // PidTotalAmt:number  ;
    // PidSysMan:string  ;
    // PidBalType:string  ;
    // PidActConfirmDate:string  ;
    // PidFmtOpbal:number  ;
    // PidNextOpbal:string  ;
    }