export const COMMON_VALUES = {

    QUOTATION_STATUS_INITIAL: 'INITIAL',
    QUOTATION_STATUS_REVISED: 'REVISED',
    QUOTATION_STATUS_REALISED: 'REALISED',
    LIFE_ASSURE_TYPE_1: 'Life1',
    LIFE_ASSURE_TYPE_2: 'Life2',


    TCS_LOGIN_USER: 'JANAKATEST',
    TCS_LOGIN_PWD: 'test@2017',
    TCS_LOGIN_BRANCH_CODE: 'HDO',
    TCS_LOGIN_ROLE_CODE: 'SUPERUSER'



};